project:
  type: website
  output-dir: _site

website:
  title: "R+AI 2025"
  favicon: images/favicon.ico
  site-url: "https://rconsortium.github.io/RplusAI_website/"
  google-analytics: "G-B697SX1BNN"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Call for Proposals
        href: cfp.qmd
      - text: Code of Conduct
        href: attend.qmd

format:
  html:
    theme: cosmo
    toc: true